FROM nginx:latest
LABEL project="expense"\
      environment="dev"\
      version="v1"
# label is to add information about image, no functionality
# we can see these labels using "docker inspect <image-name>/<container-name>"