FROM almalinux:9
# CMD ["ping","google.com"]

# if we are using just above code,we can override the above
# i.e "docker run ping facebook.com"

ENTRYPOINT ["ping","google.com"]
# if we are using ENTRYPOINT instead of CMD, we cannot ovveride
